# Generated by Django 5.2.1 on 2025-06-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamento', '0001_initial'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='servico.servico'),
        ),
    ]
