# Generated by Django 5.1 on 2025-06-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0003_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendentep', max_length=15),
        ),
    ]
