# Generated by Django 5.2.1 on 2025-06-23 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0004_alter_agendamento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=15),
        ),
    ]
