# Generated by Django 5.2.1 on 2025-05-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(default=None, max_length=150)),
                ('username', models.CharField(default=None, max_length=30, unique=True)),
                ('cpf', models.CharField(default=None, max_length=11, unique=True)),
                ('celular', models.CharField(default=None, max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
