# Generated by Django 5.2.1 on 2025-05-26 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='username',
        ),
    ]
