# Generated by Django 5.2.1 on 2025-05-26 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_remove_cliente_last_login_remove_cliente_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nome',
        ),
    ]
