# Generated by Django 5.2.1 on 2025-06-05 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profissional', '0002_alter_profissional_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('profissional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='profissional.profissional')),
            ],
        ),
    ]
