# Generated by Django 5.2.1 on 2025-06-05 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0002_alter_profissional_user'),
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='profissional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='profissional.profissional'),
        ),
    ]
