# Generated by Django 5.2.1 on 2025-09-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0004_remove_despesa_categoria_remove_receita_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], default='Outro', max_length=30, verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], default='Outro', max_length=30, verbose_name='Categoria'),
        ),
    ]
