# Generated by Django 5.2.1 on 2025-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0002_alter_profissional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='funcao',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
