# Generated by Django 5.2.1 on 2025-06-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0003_profissional_funcao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissional',
            name='nome',
        ),
    ]
