# Generated by Django 5.2.1 on 2025-06-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0004_remove_profissional_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='funcao',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
