# Generated by Django 5.2.1 on 2025-06-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0005_alter_profissional_funcao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='funcao',
            field=models.CharField(max_length=150),
        ),
    ]
