# Generated by Django 5.2.1 on 2025-06-23 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profissional', '0007_alter_profissional_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissional',
            name='celular',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='profissional',
            name='cpf',
            field=models.BigIntegerField(unique=True),
        ),
    ]
