# Generated by Django 5.2.1 on 2025-09-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0003_alter_receita_categoria_alter_receita_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='categoria',
        ),
        migrations.AddField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável'), ('outro', 'Outro')], default='Variavel', max_length=20),
        ),
        migrations.AddField(
            model_name='receita',
            name='tipo',
            field=models.CharField(choices=[('fixa', 'Fixa'), ('variavel', 'Variável'), ('outro', 'Outro')], default='Variavel', max_length=20),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
